#! /bin/sh

bspc rule -a lxappearance desktop='^2'

# autostart
$HOME/.config/bspwm/scripts/autostart.sh &
pgrep -x sxhkd > /dev/null || sxhkd &

# monitor 
bspc monitor DisplayPort-0 -d 1 2 3 
bspc monitor HDMI-A-0 -d 4 5 6

bspc config border_width 3
bspc config window_gap 16
bspc config top_padding 5
bspc config bottom_padding 5
bspc config left_padding 5
bspc config right_padding 5

bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config split_ratio 0.5

bspc config normal_border_color "#000000#"
bspc config focused_border_color "#ffffff"
bspc config focus_follows_pointer true
